tap "codeclimate/formulae"
tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask", "https://mirrors.tuna.tsinghua.edu.cn/git/homebrew/homebrew-core.git"
tap "homebrew/core", "https://mirrors.tuna.tsinghua.edu.cn/git/homebrew/homebrew-cask.git"
tap "homebrew/services"
brew "proxychains-ng"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"
brew "git"
cask "appcleaner"
cask "dingtalk"
cask "google-chrome"
cask "iterm2"
cask "jetbrains-toolbox"
cask "macdown"
cask "neteasemusic"
cask "qq"
cask "wechat"
cask "youdaodict"
cask "swish"
cask "deepl"
