tap "homebrew/cask"

brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"
brew "unrar"
cask "appcleaner"
cask "iterm2"
cask "macdown"
cask "qq"
cask "wechat"
cask "dingtalk"
cask "github"
cask "jetbrains-toolbox"
cask "neteasemusic"
cask "shadowsocksx-ng"
cask "youdaodict"
